list: $/techmobi/multidb/models/domain/columns.yaml
modelClass: Techmobi\Multidb\Models\Domain
title: Domains
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'techmobi/multidb/domains/update/:id'
